spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=9702310451&useUnicode=true
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /manager
  port: 8086

swagger:
  groupName: manager
  basePackage: com.csz.manager.controller

logging:
  level:
    com.googlecode.jsonrpc4j: debug

